### ISSUE TITLE
Have any tips for developing configuration JSON?

### ISSUE THREAD

**Issue by sgleske-ias** [SergK/nexus3-ssl#4]
Regarding the configuration JSON in https://github.com/SergK/nexus3-ssl/tree/master/nexus/json

Is there any easy way to get JSON from my current configuration?  How did you build out and write those JSON files?  I have been reading Nexus documentation on scripting but it's not really clear to me.

Thanks in advance!

**Comment by samrocketman** [comment]
I may have found my answer https://www.tikalk.com/devops/Automating_Nexus_3x/
